name: Release

on:
  push:
    tags:
      - v*

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - run: npm install
      - uses: JS-DevTools/npm-publish@v3
        id: publish
        with:
          token: ${{ secrets.NPM_TOKEN }}
          access: 'public'
      # see https://github.com/softprops/action-gh-release/pull/372#issuecomment-1642643937
      - name: Create release notes
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v5
        # with:
          # token: ${{ github.token }}
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          # token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ github.ref }}
          name: Release ${{ github.ref_name }}
          # generate_release_notes: true
          body: |
            ${{ steps.build_changelog.outputs.changelog }}

            NPM release: https://npmjs.com/package/${{ steps.publish.outputs.name }}/v/${{ steps.publish.outputs.version }}
          draft: true
          prerelease: ${{ contains(github.ref_name, '-') }}
