name: Version

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'npm version semver level'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  version:
    name: Push ${{ inputs.version }} tag
    runs-on: ubuntu-latest

    # permissions:
      # contents: write

    steps:
    - name: Checkout branch
      uses: actions/checkout@v4
      with:
      # see https://github.com/orgs/community/discussions/25617#discussioncomment-3248494
        token: ${{ secrets.RELEASE_TOKEN }}
    - uses: actions/setup-node@v4
      with:
        node-version: 22.x
    # - name: Install dependencies
      # run: npm ci --ignore-scripts
    # - name: Post-install scripts
      # run: npm rebuild && npm run prepare --if-present
    # - name: Build
      # run: npm run build
    - name: Configure git user
      run: |
        git config --global user.name "${{ github.actor }}"
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"
    - name: NPM version
      run: echo "version=$(npm version ${{ inputs.version }})" >> $GITHUB_ENV
    - name: Git push
      run: git push && git push origin ${{ env.version }}
